Fix call to delocate-wheel

diff --git a/vehicle-python-core/scripts/build-wheels b/vehicle-python-core/scripts/build-wheels
--- a/vehicle-python-core/scripts/build-wheels
+++ b/vehicle-python-core/scripts/build-wheels
@@ -22,21 +22,13 @@ eval "$(${pyenv} init -)"
 set -- "3.7" "3.8" "3.9" "3.10" "3.11"
 for python_version in "$@"
 do
-    pyenv_output="$(pyenv shell "${python_version}" 2>&1 || echo > "$fail")"
+    pyenv shell "${python_version}" || echo > "$fail"
     if [ -s "$fail" ]
     then
-        if [ "${pyenv_output}" = "pyenv: version \`${python_version}' not installed" ]
-        then
-            echo "Error: Python ${python_version} is not installed. Install it by running:"
-            echo
-            echo "  pyenv install ${python_version}"
-            echo
-            exit 1
-        elif [ "${pyenv_output}" != "" ]
-        then
-            >&2 echo "${pyenv_output}"
-        fi
+        >&2 echo "pyenv: install with \`pyenv install ${python_version}'"
+        exit 1
     else
+        echo "$(python --version)"
         python -m pip install -r "${ROOT_DIR}/requirements-ci.txt"
         python -m pipx run --spec build pyproject-build --wheel --outdir="${ROOT_DIR}/wheelhouselocal"
     fi
@@ -57,7 +49,7 @@ mkdir -p "${ROOT_DIR}/wheelhouse"
 case "${PLATFORM}" in
     'darwin')
         python -m pip install -r "${ROOT_DIR}/requirements-ci.txt"
-        python -m pipx run delocate-wheel --wheel-dir="${ROOT_DIR}/wheelhouse" "${ROOT_DIR}/wheelhouselocal"/*.whl
+        python -m pipx run --spec delocate delocate-wheel --wheel-dir="${ROOT_DIR}/wheelhouse" "${ROOT_DIR}/wheelhouselocal"/*.whl
     ;;
     'linux')
         LIBC="$(python -c 'import platform; print(platform.libc_ver()[1].replace(".","_"))')"
