Fix error tests

diff --git a/script/format-haskell b/script/format-haskell
--- a/script/format-haskell
+++ b/script/format-haskell
@@ -25,7 +25,10 @@ then
         fi
     done
 else
-    echo "\033[1;33mWarning: could not find 'stylish-haskell'\033[0m" 1>&2
+    echo "\033[0;31mError: Could not find stylish-haskell.\033[0m" 1>&2
+    echo "\033[0;31m       Install stylish-haskell or commit with SKIP=format-haskell\033[0m"
+    echo "\033[0;31m       See: https://github.com/haskell/stylish-haskell#readme\033[0m"
+    exit 1
 fi
 
 # Test if the file "$fail" exists and has size greater than zero:
