Add ghc-debug and nothunks instrumentation

diff --git a/scripts/vehicle-profile b/scripts/vehicle-profile
--- a/scripts/vehicle-profile
+++ b/scripts/vehicle-profile
@@ -3,6 +3,20 @@
 # POSIX compliant method for 'pipefail':
 fail=$(mktemp)
 
+# Check if 'eventlog2html' is on the PATH:
+EVENTLOG2HTML=$(which eventlog2html || echo > "$fail")
+
+if [ -s "$fail" ]; then
+    rm "$fail"
+    echo "The vehicle-profile script 'eventlog2html' to visualise the event log."
+    echo "You can install 'eventlog2html' by running:"
+    echo
+    echo "  cabal v2-install eventlog2html --ignore-project --overwrite-policy=always"
+    echo
+    echo "See: https://mpickering.github.io/eventlog2html/"
+    exit 1
+fi
+
 # Check the HEAP_PROFILE_TYPE setting:
 HEAP_PROFILE_TYPE="${HEAP_PROFILE_TYPE--hT}"
 if [ "$HEAP_PROFILE_TYPE" = "-hT" ]; then
@@ -26,11 +40,10 @@ EVENTLOG_FILE="$PROFILING_PREFIX$HEAP_PROFILE_TYPE.eventlog"
 # Run vehicle in debug mode with the given options.
 # Produce a heap profile grouped by closure type (-hT).
 RTSOPTS="+RTS -po"$PROFILING_PREFIX" -ol"$EVENTLOG_FILE" -s -l "${HEAP_PROFILE_TYPE}" -RTS"
-VEHICLE="cabal -v0 --project-file=cabal.project.debug run exe:vehicle --"
+VEHICLE="cabal -v0 --project-file=cabal.project.profile run vehicle:exe:vehicle --"
 [ ! -s "$fail" ] && ($VEHICLE $@ $RTSOPTS || echo > "$fail")
 
 # Convert the heap profile to an HTML page.
-EVENTLOG2HTML="eventlog2html"
 [ ! -s "$fail" ] && ($EVENTLOG2HTML "$EVENTLOG_FILE" || echo > "$fail")
 
 # Output the path to the generated HTML page.
@@ -45,27 +58,22 @@ else
   rm "$fail"
 fi
 
-# Open the eventlog in a browser
-# See: https://en.wikipedia.org/wiki/Uname#Examples
-OPERATING_SYSTEM=$(uname -s)
-if [ "$OPERATING_SYSTEM" = "Darwin" ]
-then
-  open "$EVENTLOG_HTML"
-elif [ "$OPERATING_SYSTEM" = "Linux" ]
-then
-  # Use BROWSER environment variable?
-  # [ "$BROWSER" = "" ] || $BROWSER "$EVENTLOG_HTML"
-  :
+# Get the current platform
+SYSTEM=$(uname -s | cut -d- -f1)
+if [ "$SYSTEM" = "CYGWIN_NT" \
+  -o "$SYSTEM" = "MINGW32_NT" \
+  -o "$SYSTEM" = "MINGW64_NT" \
+  -o "$SYSTEM" = "MSYS_NT" ]; then
+  PLATFORM="Windows"
+elif [ "$SYSTEM" = "Darwin" ]; then
+  PLATFORM="macOS"
+elif [ "$SYSTEM" = "Linux" ]; then
+  PLATFORM="Linux"
 else
-  OPERATING_SYSTEM="$(echo "$OPERATING_SYSTEM" | cut -d - -f 1)"
-  if [ "$OPERATING_SYSTEM" = "CYGWIN_NT" \
-    -o "$OPERATING_SYSTEM" = "MINGW64_NT" \
-    -o "$OPERATING_SYSTEM" = "MSYS_NT" ]; then
-    # Use default browser on Windows? Open via PowerShell?
-    # start "" "$EVENTLOG_HTML"
-    :
-  else
-    # Unsupported operating system?
-    :
-  fi
+  echo "WARNING: Could not determine platform" >&2
+fi
+
+# Open the eventlog in a browser
+if [ "$PLATFORM" = "macOS" ]; then
+  open "$EVENTLOG_HTML"
 fi
