Better error reporting in vehicle-profile-heap

diff --git a/scripts/vehicle-profile-heap b/scripts/vehicle-profile-heap
--- a/scripts/vehicle-profile-heap
+++ b/scripts/vehicle-profile-heap
@@ -20,12 +20,12 @@ fi
 # Check the HEAP_PROFILE_TYPE setting:
 HEAP_PROFILE_TYPE="${HEAP_PROFILE_TYPE--hT}"
 if [ "$HEAP_PROFILE_TYPE" = "-hT" ]; then
-  echo "Type of profile: Basic heap profile"
-elif [ "$HEAP_PROFILE_TYPE" = "-hi" ]; then
-  echo "Type of profile: Info table profile"
+    echo "Type of profile: Basic heap profile"
+    elif [ "$HEAP_PROFILE_TYPE" = "-hi" ]; then
+    echo "Type of profile: Info table profile"
 else
-  echo "Usage: HEAP_PROFILE_TYPE=[-hT or -hi] ./scripts/vehicle-profile [VEHICLE OPTIONS]"
-  echo "Error: expected HEAP_PROFILE_TYPE to be -hT or -hi, found $HEAP_PROFILE_TYPE"
+    echo "Usage: HEAP_PROFILE_TYPE=[-hT or -hi] ./scripts/vehicle-profile [VEHICLE OPTIONS]"
+    echo "Error: expected HEAP_PROFILE_TYPE to be -hT or -hi, found $HEAP_PROFILE_TYPE"
 fi
 
 # Create the directory for profiling files:
@@ -36,44 +36,64 @@ PROFILING_DIR=".profiling"
 TIMESTAMP=$(awk 'BEGIN{srand(); print srand()}')
 PROFILING_PREFIX="$PROFILING_DIR/vehicle-$TIMESTAMP"
 EVENTLOG_FILE="$PROFILING_PREFIX$HEAP_PROFILE_TYPE.eventlog"
+EVENTLOG_HTML="$EVENTLOG_FILE.html"
+
+# On interrupt, kill Vehicle and reset trap.
+_on_interrupt() {
+    echo "Forward SIGINT to Vehicle"
+    kill -INT "$PID_VEHICLE" 2>/dev/null
+    trap - INT
+}
+trap _on_interrupt INT
 
 # Run vehicle in debug mode with the given options.
 # Produce a heap profile grouped by closure type (-hT).
-RTSOPTS="+RTS -po"$PROFILING_PREFIX" -ol"$EVENTLOG_FILE" -s -l "${HEAP_PROFILE_TYPE}" -RTS"
+RTSOPTS="+RTS -po$PROFILING_PREFIX -ol$EVENTLOG_FILE -s -l ${HEAP_PROFILE_TYPE} -RTS"
 VEHICLE="cabal -v0 --project-file=cabal.project.profile-heap run vehicle:exe:vehicle --"
-[ ! -s "$fail" ] && ($VEHICLE $@ $RTSOPTS || echo > "$fail")
+if [ ! -s "$fail" ]; then
+    echo "$VEHICLE $@ $RTSOPTS"
+    $VEHICLE $@ $RTSOPTS || echo > "$fail" &
+    VEHICLE_PID=$!
+    wait "$VEHICLE_PID"
+    trap - INT
+fi
 
-# Convert the heap profile to an HTML page.
-[ ! -s "$fail" ] && ($EVENTLOG2HTML "$EVENTLOG_FILE" || echo > "$fail")
+# If an eventlog was generated, convert and open it.
+if [ ! -s "$fail" ] && [ -f "$EVENTLOG_FILE" ]; then
+    # Convert the heap profile to an HTML page.
+    $EVENTLOG2HTML "$EVENTLOG_FILE" || echo > "$fail"
 
-# Output the path to the generated HTML page.
-EVENTLOG_HTML="$EVENTLOG_FILE.html"
-[ ! -s "$fail" ] && (echo "Wrote eventlog to $EVENTLOG_FILE.html")
+    # Output the path to the generated HTML page.
+    [ ! -s "$fail" ] && [ -f "$EVENTLOG_HTML" ] && (echo "Wrote eventlog to $EVENTLOG_FILE.html")
+
+    # Get the current platform
+    SYSTEM=$(uname -s | cut -d- -f1)
+    if [ "$SYSTEM" = "CYGWIN_NT"  ] || \
+    [ "$SYSTEM" = "MINGW32_NT" ] || \
+    [ "$SYSTEM" = "MINGW64_NT" ] || \
+    [ "$SYSTEM" = "MSYS_NT"    ]; then
+        PLATFORM="Windows"
+        elif [ "$SYSTEM" = "Darwin" ]; then
+        PLATFORM="macOS"
+        elif [ "$SYSTEM" = "Linux" ]; then
+        PLATFORM="Linux"
+    else
+        echo "WARNING: Could not determine platform" >&2
+    fi
+
+    # Open the eventlog in a browser
+    if [ "$PLATFORM" = "macOS" ]; then
+        open "$EVENTLOG_HTML"
+    fi
+else
+    echo "No eventlog was generated; did you kill the process too soon?"
+    exit 1
+fi
 
 # Check whether or not any subcommand failed:
 if [ -s "$fail" ]; then
-  rm "$fail"
-  exit 1
+    rm "$fail"
+    exit 1
 else
-  rm "$fail"
-fi
-
-# Get the current platform
-SYSTEM=$(uname -s | cut -d- -f1)
-if [ "$SYSTEM" = "CYGWIN_NT" \
-  -o "$SYSTEM" = "MINGW32_NT" \
-  -o "$SYSTEM" = "MINGW64_NT" \
-  -o "$SYSTEM" = "MSYS_NT" ]; then
-  PLATFORM="Windows"
-elif [ "$SYSTEM" = "Darwin" ]; then
-  PLATFORM="macOS"
-elif [ "$SYSTEM" = "Linux" ]; then
-  PLATFORM="Linux"
-else
-  echo "WARNING: Could not determine platform" >&2
-fi
-
-# Open the eventlog in a browser
-if [ "$PLATFORM" = "macOS" ]; then
-  open "$EVENTLOG_HTML"
+    rm "$fail"
 fi
